version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  default:
    working_directory: ~/mattermost-webapp
    docker:
      - image: mattermost/mattermost-build-webapp:oct-2-2018

aliases:
  - &restore_cache
    restore_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
  - &save_cache
    save_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

jobs:
  install:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: |
          npm ci
          cd node_modules/mattermost-redux && npm i && npm run build
      - *save_cache

  lint:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: |
          npm run check

  test:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: npm run test-ci
      - store_test_results:
          path: build/

  build:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: make package-ci
      - store_artifacts:
          path: ~/mattermost-webapp/mattermost-webapp.tar.gz
      - persist_to_workspace:
          root: .
          paths: .

  upload-s3:
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: .
      - aws-s3/copy:
          from: mattermost-webapp.tar.gz
          to: s3://pr-builds.mattermost.com/${CIRCLE_PROJECT_REPONAME}/$(echo "${CIRCLE_BRANCH}" | sed 's/pull\//PR-/g')/
          arguments: --cache-control no-cache
      - aws-s3/copy:
          from: mattermost-webapp.tar.gz
          to: s3://pr-builds.mattermost.com/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1}/
          arguments: --cache-control no-cache

workflows:
  version: 2
  untagged-build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - upload-s3:
          context: mattermost-ci-pr-builds-s3
          requires:
            - build
